# Generated by Django 4.1 on 2023-05-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='invoice_status',
            field=models.CharField(choices=[('NR', 'Not ready to request'), ('READY', 'Ready to request'), ('REQ', 'Requested'), ('REC', 'Received via upload'), ('REC2', 'Received (direct PDF/paper)'), ('ERR', 'Error on upload'), ('PAID', 'Paid'), ('NA', 'No Invoice')], default='NR', max_length=50),
        ),
    ]
