# Generated by Django 4.2.1 on 2023-05-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_alter_cost_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='currency',
            field=models.CharField(choices=[('JPY', 'JPY ¥'), ('USD', 'USD $'), ('CAD', 'CAD $'), ('AUD', 'AUD $'), ('EUR', 'EUR €'), ('GBP', 'GBP £'), ('THB', 'THB ฿')], default='¥', max_length=10),
        ),
    ]
