version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/New_Pipeline/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    # depends_on:
    #   - db
  # db:
  #   image: postgres:14-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=linpostgres
  #     - POSTGRES_PASSWORD=2,yncCd6rZFieZxg
  #     - POSTGRES_DB=postgres

# volumes:
#   postgres_data:
