version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    image: npt_prod:latest
    command: gunicorn New_Pipeline.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
    - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    image: npt_nginx_prod:latest
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: