services:
  web:
    image: ghcr.io/phoenixudon/new_pipeline/web:${TAG}
    command: gunicorn New_Pipeline.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
    - 8000
    env_file:
      - ./.env
  nginx:
    image: ghcr.io/phoenixudon/new_pipeline/nginx:${TAG}
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - /root/certs/bwcat.tools.key:/root/certs/bwcat.tools.key
      - /root/certs/bwcat_tools_chain.crt:/root/certs/bwcat_tools_chain.crt

    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: