services:
  web:
    image: ghcr.io/phoenixudon/new_pipeline/web:latest
    command: gunicorn New_Pipeline.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
    - 8000
    env_file:
      - ./.env
  nginx:
    image: ghcr.io/phoenixudon/new_pipeline/nginx:latest
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env
      
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: