# Generated by Django 4.2.1 on 2023-10-06 08:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=100, unique=True)),
                ('proper_name', models.CharField(blank=True, max_length=100, null=True)),
                ('proper_name_japanese', models.CharField(blank=True, max_length=100)),
                ('job_code_prefix', models.CharField(max_length=4, unique=True)),
                ('paymentTerm', models.CharField(choices=[('NET30', 'Net 30'), ('NET60', 'Net 60'), ('NET90', 'Net 90'), ('Unknown', 'Unknown'), ('Special', 'Special'), ('N/A', 'N/A'), ('None', '')], default='None', max_length=7, null=True)),
                ('notes', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30)),
                ('amount', models.IntegerField(null=True)),
                ('currency', models.CharField(choices=[('JPY', 'JPY ¥'), ('USD', 'USD $'), ('CAD', 'CAD $'), ('AUD', 'AUD $'), ('EUR', 'EUR €'), ('GBP', 'GBP £'), ('THB', 'THB ฿')], default='¥', max_length=10)),
                ('invoice_status', models.CharField(choices=[('NR', 'Not requested'), ('REQ', 'Requested'), ('REC', 'Received via upload'), ('REC2', 'Received (direct PDF/paper)'), ('ERR', 'Error on upload'), ('QUE', 'Queued for payment'), ('PAID', 'Paid'), ('NA', 'No Invoice')], default='NR', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('PO_number', models.CharField(default=None, editable=False, max_length=10, null=True)),
                ('PO_num_is_fixed', models.BooleanField(default=False)),
                ('locked_exchange_rate', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=10, null=True)),
                ('exchange_rate_locked_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('exchange_rate_override', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=50)),
                ('job_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('job_code_isFixed', models.BooleanField(default=False)),
                ('job_code_isOverridden', models.BooleanField(default=False)),
                ('custom_job_code', models.CharField(blank=True, max_length=15, null=True)),
                ('isArchived', models.BooleanField(default=False)),
                ('isInvoiced', models.BooleanField(default=False)),
                ('revenue', models.IntegerField()),
                ('granular_revenue', models.BooleanField(default=False)),
                ('add_consumption_tax', models.BooleanField(default=True)),
                ('consumption_tax_amt', models.IntegerField(blank=True, null=True)),
                ('revenue_incl_tax', models.IntegerField(editable=False, null=True)),
                ('invoice_name', models.CharField(blank=True, max_length=100, null=True)),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
                ('job_date', models.DateField(editable=False, null=True)),
                ('job_type', models.CharField(choices=[('ORIGINAL', 'Original Music'), ('RENEWAL', 'Renewal'), ('LIBRARY', 'Library'), ('LICENSING', 'Licensing'), ('LOGO', 'Sound Logo'), ('MISC', 'Misc'), ('RETAINER', 'Retainer')], default='ORIGINAL', max_length=15)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('personInCharge', models.CharField(choices=[(None, 'Select PIC'), ('ER', 'Erik Reiff'), ('JC', 'Joe Connor'), ('KD', 'Kenny Dallas'), ('MH', 'Maria Hasegawa'), ('RI', 'Ryu Ishizawa'), ('SM', 'Seiya Matsumiya'), ('TO', 'Timo Otsuki')], max_length=2)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('READYTOINV', 'Ready to Invoice'), ('INVOICED1', 'Invoiced'), ('INVOICED2', 'Invoiced (canc.)'), ('FINISHED', 'Finished'), ('ARCHIVED', 'Archived')], default='ONGOING', max_length=14)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('vendor_code', models.CharField(max_length=4, null=True, unique=True)),
                ('kanji_name', models.CharField(blank=True, max_length=10)),
                ('kana_name', models.CharField(blank=True, max_length=12)),
                ('use_company_name', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('preferred_currency', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('company_name__isnull', False), ('first_name__isnull', True)), models.Q(('company_name__isnull', True), ('first_name__isnull', False)), models.Q(('company_name__isnull', False), ('first_name__isnull', False)), _connector='OR'), name='pipeline_vendor_is_person_or_company'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_by_client', to='pipeline.client'),
        ),
        migrations.AddField(
            model_name='job',
            name='invoice_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.client'),
        ),
        migrations.AddField(
            model_name='job',
            name='relatedJobs',
            field=models.ManyToManyField(blank=True, to='pipeline.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='jobs_rel', to='pipeline.vendor', verbose_name='vendors involved'),
        ),
        migrations.AddField(
            model_name='cost',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_rel', to='pipeline.job'),
        ),
        migrations.AddField(
            model_name='cost',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_rel', to='pipeline.vendor'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('proper_name__isnull', True), ('proper_name_japanese__isnull', False)), models.Q(('proper_name__isnull', False), ('proper_name_japanese__isnull', True)), models.Q(('proper_name__isnull', False), ('proper_name_japanese__isnull', False)), _connector='OR'), name='pipeline_client_has_proper_name'),
        ),
    ]
