# Generated by Django 4.2.1 on 2023-10-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='month',
            new_name='invoice_month',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='year',
            new_name='invoice_year',
        ),
    ]
