# Generated by Django 4.2.1 on 2023-10-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_rename_month_job_invoice_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_code_isFixed',
            new_name='job_code_is_fixed',
        ),
    ]
