# Generated by Django 4.2.1 on 2023-10-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_rename_job_code_isfixed_job_job_code_is_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='pay_period',
            field=models.DateField(null=True),
        ),
    ]
