# Generated by Django 4.2.1 on 2023-11-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_cost_pay_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='jobs',
            field=models.ManyToManyField(to='pipeline.job'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs_of_job', to='pipeline.job'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs_by_vendor', to='pipeline.vendor'),
        ),
        migrations.AlterField(
            model_name='job',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='jobs_with_vendor', to='pipeline.vendor', verbose_name='vendors involved'),
        ),
    ]
