# Generated by Django 4.2.1 on 2023-05-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_remove_vendor_vendor_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_code_letters',
            new_name='vendor_code',
        ),
    ]
