# Generated by Django 4.2.1 on 2023-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_rename_vendor_code_letters_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='PO_number',
            field=models.CharField(default=None, editable=False, max_length=10, null=True),
        ),
    ]
