# Generated by Django 4.2.1 on 2023-05-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_alter_cost_po_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('company_name__isnull', False), ('first_name__isnull', True), ('last_name__isnull', True)), models.Q(('company_name__isnull', True), ('first_name__isnull', False), ('last_name__isnull', False)), models.Q(('company_name__isnull', False), ('first_name__isnull', False), ('last_name__isnull', False)), _connector='OR'), name='pipeline_vendor_is_person_or_company'),
        ),
    ]
