# Generated by Django 4.2.1 on 2023-05-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_vendor_pipeline_vendor_is_person_or_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
