# Generated by Django 4.2.1 on 2023-05-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_alter_vendor_first_name_alter_vendor_last_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendor',
            name='pipeline_vendor_is_person_or_company',
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('company_name__isnull', False), ('first_name__isnull', True)), models.Q(('company_name__isnull', True), ('first_name__isnull', False)), models.Q(('company_name__isnull', False), ('first_name__isnull', False)), _connector='OR'), name='pipeline_vendor_is_person_or_company'),
        ),
    ]
