# Generated by Django 4.2.1 on 2023-06-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_remove_vendor_pipeline_vendor_is_person_or_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='month',
            field=models.CharField(default=6, max_length=2),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
