# Generated by Django 4.2.1 on 2023-06-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_alter_job_month_alter_vendor_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='revenue',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
