# Generated by Django 4.2.1 on 2023-06-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0012_alter_job_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='revenue',
            field=models.IntegerField(),
        ),
    ]
