# Generated by Django 4.2.1 on 2023-06-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0014_job_add_consumption_tax_alter_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='invoiceName',
            new_name='invoice_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='paidTo',
            new_name='paid_to',
        ),
        migrations.AlterField(
            model_name='cost',
            name='invoice_status',
            field=models.CharField(choices=[('NR', 'Not requested'), ('REQ', 'Requested'), ('REC', 'Received via upload'), ('REC2', 'Received (direct PDF/paper)'), ('ERR', 'Error on upload'), ('QUE', 'Queued for payment'), ('PAID', 'Paid'), ('NA', 'No Invoice')], default='NR', max_length=50),
        ),
    ]
