# Generated by Django 4.2.1 on 2023-06-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0015_rename_invoicename_job_invoice_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='paid_to',
            new_name='invoice_recipient',
        ),
    ]
