# Generated by Django 4.2.1 on 2023-06-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0018_job_invoice_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('ONGOING', 'Ongoing'), ('INVOICED1', 'Completed & Invoiced'), ('INVOICED2', 'Cancelled & Invoiced'), ('FINISHED', 'Finished'), ('ARCHIVED', 'Archived')], default='ONGOING', max_length=14),
        ),
    ]
