# Generated by Django 4.2.1 on 2023-07-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0019_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('ORIGINAL', 'Original Music'), ('RENEWAL', 'Renewal'), ('LIBRARY', 'Library'), ('LICENSING', 'Licensing'), ('LOGO', 'Sound Logo'), ('MISC', 'Misc'), ('RETAINER', 'Retainer')], default='ORIGINAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='month',
            field=models.CharField(default=7, max_length=2),
        ),
    ]
