# Generated by Django 4.2.1 on 2023-07-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0020_alter_job_job_type_alter_job_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
