# Generated by Django 4.2.1 on 2023-07-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0021_alter_job_job_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name_japanese',
        ),
        migrations.AddField(
            model_name='job',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
