# Generated by Django 4.2.1 on 2023-07-18 08:17
from django.db import migrations, models
from pipeline.models import Job

def update_existing_objects(apps, schema_editor):
    obj = apps.get_model('pipeline', 'Job')
    for obj in Job.objects.all():
        obj.consumption_tax_amt = Job.get_consumption_tax_amt(obj)
        obj.revenue_incl_consumption_tax = Job.get_consumption_tax_amt(obj) + obj.revenue
        obj.save()

def reverse_update_existing_objects(apps, schema_editor):
    obj = apps.get_model('pipeline', 'Job')
    for obj in Job.objects.all():
        obj.consumption_tax_amt = None
        obj.revenue_incl_consumption_tax = None
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0022_remove_client_name_japanese_job_deposit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='consumption_tax_amt',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='revenue_incl_consumption_tax',
            field=models.IntegerField(editable=False, null=True),
        ),

        migrations.RunPython(update_existing_objects, reverse_update_existing_objects),
    ]
    
