# Generated by Django 4.2.1 on 2023-08-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0024_rename_revenue_incl_consumption_tax_job_revenue_incl_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='granular_revenue',
            field=models.BooleanField(default=False),
        ),
    ]
