# Generated by Django 4.2.1 on 2023-09-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0025_job_granular_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='preferred_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='month',
            field=models.CharField(max_length=2),
        ),
    ]
