# Generated by Django 4.2.1 on 2023-09-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0026_vendor_preferred_currency_alter_job_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
