# Generated by Django 4.2.1 on 2023-09-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0027_alter_job_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
