# Generated by Django 4.2.1 on 2023-09-22 01:13

from django.db import migrations
from django.utils import timezone

def set_date_to_none(apps, schema_editor):
    Job = apps.get_model('pipeline', 'Job')
    Job.objects.filter(status='ONGOING').update(month=None, year=None, job_date=None)

def reverse_migration(apps, schema_editor):
    today = timezone.now()
    month=timezone.now().month, 
    year=timezone.now().year,
    Job = apps.get_model('pipeline', 'Job')
    Job.objects.filter(status='ONGOING').update(
        month=month,
        year=year,
        job_date=f'{year}-{int(month):02d}-01' if (year and month) else None)

class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0028_alter_job_month_alter_job_year'),
    ]

    operations = [
        migrations.RunPython(set_date_to_none, reverse_migration)
    ]
