# Generated by Django 4.1 on 2023-03-25 09:52

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20230325_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
