# Generated by Django 4.1 on 2023-04-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230325_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='month',
            field=models.CharField(default=4, max_length=2),
        ),
    ]
