# Generated by Django 4.1 on 2023-04-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_job_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='budget',
            new_name='revenue',
        ),
    ]
