# Generated by Django 3.2.15 on 2023-02-01 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('proper_name', models.CharField(blank=True, max_length=30)),
                ('job_code_prefix', models.CharField(blank=True, max_length=4, unique=True)),
                ('paymentTerm', models.CharField(choices=[('NET30', 'Net 30'), ('NET60', 'Net 60'), ('NET90', 'Net 90'), ('Unknown', 'Unknown'), ('Special', 'Special'), ('N/A', 'N/A'), ('None', '')], default='None', max_length=7)),
                ('notes', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='NewVendor', max_length=30)),
                ('vendor_initials', models.CharField(max_length=4)),
                ('vendor_unique_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('kanji_name', models.CharField(blank=True, max_length=10)),
                ('kana_name', models.CharField(blank=True, max_length=12)),
                ('company_name', models.CharField(blank=True, max_length=12)),
                ('notes', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default='New Job', max_length=50)),
                ('job_code', models.CharField(max_length=11, unique=True)),
                ('job_type', models.CharField(choices=[('RENEWAL', 'Renewal'), ('ORIGINAL', 'Original'), ('LIBRARY', 'Library'), ('LICENSING', 'Licensing'), ('MISC', 'Misc')], default='Original', max_length=15)),
                ('budget', models.IntegerField(default=100000)),
                ('cost', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
                ('profit_rate', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('personInCharge', models.CharField(blank=True, choices=[('ER', 'Erik Reiff'), ('JC', 'Joe Connor'), ('KD', 'Kenny Dallas'), ('MH', 'Maria Hasegawa'), ('RI', 'Ryu Ishizawa'), ('SM', 'Seiya Matsumiya'), ('TO', 'Timo Otsuki')], max_length=2)),
                ('status', models.CharField(choices=[('LEAD', 'Lead'), ('ONGOING', 'Ongoing'), ('INVOICED', 'Invoiced'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled'), ('ARCHIVABLE', 'To be Archived'), ('ARCHIVED', 'Archived')], default='ONGOING', max_length=14)),
                ('job_date', models.DateField(default=django.utils.timezone.now, verbose_name='Job Date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.client')),
                ('vendors', models.ManyToManyField(blank=True, to='main_app.Vendor', verbose_name='vendors involved')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('currency', models.CharField(choices=[('JPY', 'JPY ¥'), ('USD', 'USD $'), ('CAD', 'CAD $'), ('AUD', 'AUD $'), ('EUR', 'EUR €'), ('GBP', 'GBP £')], default='JPY ¥', max_length=10)),
                ('invoice_status', models.CharField(choices=[('NOT', '--invoice status--'), ('REQ', 'Requested'), ('REC', 'Received'), ('PAID', 'Paid'), ('NA', 'No Invoice')], default='--invoice status--', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_job', to='main_app.job')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vendor')),
            ],
        ),
    ]
