# Generated by Django 3.2.15 on 2023-02-02 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='job',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='job',
            name='profit_rate',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_unique_id',
        ),
        migrations.AddField(
            model_name='vendor',
            name='unique_id',
            field=models.CharField(default='NEW000', max_length=10),
        ),
        migrations.AlterField(
            model_name='cost',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.job'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
