# Generated by Django 3.2.15 on 2023-02-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20230209_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='PO_number',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
