# Generated by Django 3.2.15 on 2023-02-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20230215_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_month',
        ),
        migrations.AddField(
            model_name='job',
            name='month',
            field=models.CharField(default='02', max_length=15),
        ),
    ]
