# Generated by Django 3.2.15 on 2023-02-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_job_isinvoiced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_code_fixed',
            new_name='job_code_isFixed',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_code_overridden',
            new_name='job_code_isOverridden',
        ),
        migrations.AddField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
