# Generated by Django 3.2.15 on 2023-02-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20230217_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
    ]
