# Generated by Django 3.2.15 on 2023-02-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='relatedJob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.job'),
        ),
    ]
