# Generated by Django 3.2.15 on 2023-03-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_auto_20230228_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='allVendorInvoicesPaid',
        ),
        migrations.RemoveField(
            model_name='job',
            name='allVendorInvoicesReceived',
        ),
        migrations.AlterField(
            model_name='cost',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='month',
            field=models.CharField(default=3, max_length=2),
        ),
    ]
