# Generated by Django 4.1 on 2023-03-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_auto_20230301_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='relatedJobs',
            field=models.ManyToManyField(blank=True, to='main_app.job'),
        ),
    ]
