# Generated by Django 4.1 on 2023-03-25 09:52

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    Vendor = apps.get_model('main_app', 'Vendor')
    for row in Vendor.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_vendor_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
