# Generated by Django 4.1 on 2023-04-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_cost_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='invoice_status',
            field=models.CharField(choices=[('NR', 'Not ready to request'), ('READY', 'Ready to request'), ('REQ', 'Requested'), ('REC', 'Received via upload'), ('REC2', 'Received (direct PDF/paper)'), ('PAID', 'Paid'), ('NA', 'No Invoice')], default='NR', max_length=50),
        ),
    ]
