# Generated by Django 4.1 on 2023-05-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_cost_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='final_exchange_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='month',
            field=models.CharField(default=5, max_length=2),
        ),
    ]
