# Generated by Django 4.1 on 2023-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_cost_final_exchange_rate_alter_job_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='final_exchange_rate_override_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cost',
            name='final_exchange_rate_setdate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
