# Generated by Django 4.1 on 2023-05-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_cost_final_exchange_rate_override_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='final_exchange_rate',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='final_exchange_rate_override_date',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='final_exchange_rate_setdate',
        ),
        migrations.AddField(
            model_name='cost',
            name='exchange_rate_locked_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='exchange_rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cost',
            name='locked_exchange_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
