# Generated by Django 4.1 on 2023-05-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_cost_final_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='locked_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=10, null=True),
        ),
    ]
