# Generated by Django 4.1 on 2023-03-25 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=100, unique=True)),
                ('proper_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_japanese', models.CharField(blank=True, max_length=100, null=True)),
                ('proper_name_japanese', models.CharField(blank=True, max_length=100)),
                ('job_code_prefix', models.CharField(max_length=4, unique=True)),
                ('paymentTerm', models.CharField(choices=[('NET30', 'Net 30'), ('NET60', 'Net 60'), ('NET90', 'Net 90'), ('Unknown', 'Unknown'), ('Special', 'Special'), ('N/A', 'N/A'), ('None', '')], default='None', max_length=7, null=True)),
                ('notes', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default='NEW00', max_length=10)),
                ('full_name', models.CharField(default='NewVendor', max_length=30)),
                ('vendor_initials', models.CharField(max_length=4)),
                ('kanji_name', models.CharField(blank=True, max_length=10)),
                ('kana_name', models.CharField(blank=True, max_length=12)),
                ('company_name', models.CharField(blank=True, max_length=12)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50)),
                ('job_code', models.CharField(max_length=15, unique=True)),
                ('job_code_isFixed', models.BooleanField(default=False)),
                ('job_code_isOverridden', models.BooleanField(default=False)),
                ('custom_job_code', models.CharField(blank=True, max_length=15, null=True)),
                ('isArchived', models.BooleanField(default=False)),
                ('isInvoiced', models.BooleanField(default=False)),
                ('budget', models.IntegerField()),
                ('paidTo', models.CharField(blank=True, max_length=100)),
                ('invoiceName', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(default=2023, max_length=4)),
                ('month', models.CharField(default=3, max_length=2)),
                ('job_date', models.DateField(default=django.utils.timezone.now, editable=False, null=True)),
                ('job_type', models.CharField(choices=[('ORIGINAL', 'Original'), ('RENEWAL', 'Renewal'), ('LIBRARY', 'Library'), ('LICENSING', 'Licensing'), ('MISC', 'Misc'), ('RETAINER', 'Retainer')], default='Original', max_length=15)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('personInCharge', models.CharField(choices=[(None, 'Select PIC'), ('ER', 'Erik Reiff'), ('JC', 'Joe Connor'), ('KD', 'Kenny Dallas'), ('MH', 'Maria Hasegawa'), ('RI', 'Ryu Ishizawa'), ('SM', 'Seiya Matsumiya'), ('TO', 'Timo Otsuki')], max_length=2)),
                ('status', models.CharField(choices=[('LEAD', 'Lead'), ('ONGOING', 'Ongoing'), ('INVOICED', 'Invoiced'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled'), ('ARCHIVABLE', 'To be Archived'), ('ARCHIVED', 'Archived')], default='ONGOING', max_length=14)),
                ('isDeleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.client')),
                ('relatedJobs', models.ManyToManyField(blank=True, to='main_app.job')),
                ('vendors', models.ManyToManyField(blank=True, related_name='jobs_rel', to='main_app.vendor', verbose_name='vendors involved')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30)),
                ('amount', models.IntegerField(null=True)),
                ('currency', models.CharField(choices=[('¥', 'JPY ¥'), ('US$', 'USD $'), ('CA$', 'CAD $'), ('AU$', 'AUD $'), ('€', 'EUR €'), ('£', 'GBP £')], default='¥', max_length=10)),
                ('invoice_status', models.CharField(choices=[('NR', 'Not ready to request'), ('READY', 'Ready to request'), ('REQ', 'Requested'), ('REC', 'Received'), ('CHECK', 'Needs manual check'), ('PAID', 'Paid'), ('NA', 'No Invoice')], default='NR', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('PO_number', models.CharField(default=None, editable=False, max_length=15, null=True)),
                ('PO_num_is_fixed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_rel', to='main_app.job')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_rel', to='main_app.vendor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('proper_name__isnull', True), ('proper_name_japanese__isnull', False)), models.Q(('proper_name__isnull', False), ('proper_name_japanese__isnull', True)), models.Q(('proper_name__isnull', False), ('proper_name_japanese__isnull', False)), _connector='OR'), name='main_app_client_has_proper_name'),
        ),
    ]
