# Generated by Django 4.1 on 2023-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='job_code_prefix',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
