# Generated by Django 4.1 on 2023-03-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_client_job_code_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name_japanese',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='paymentTerm',
            field=models.CharField(choices=[('NET30', 'Net 30'), ('NET60', 'Net 60'), ('NET90', 'Net 90'), ('Unknown', 'Unknown'), ('Special', 'Special'), ('N/A', 'N/A'), ('None', '')], default='None', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='proper_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('proper_name__isnull', True), ('proper_name_japanese__isnull', False)), models.Q(('proper_name__isnull', False), ('proper_name_japanese__isnull', True)), models.Q(('proper_name__isnull', False), ('proper_name_japanese__isnull', False)), _connector='OR'), name='main_app_client_has_proper_name'),
        ),
    ]
