# Generated by Django 3.2.15 on 2023-02-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230202_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='currency',
            field=models.CharField(choices=[('¥', 'JPY ¥'), ('US$', 'USD $'), ('CA$', 'CAD $'), ('AU$', 'AUD $'), ('€', 'EUR €'), ('£', 'GBP £')], default='JPY ¥', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
