# Generated by Django 4.1 on 2023-03-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_client_name_japanese_alter_client_paymentterm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='friendly_name',
        ),
    ]
