# Generated by Django 3.2.15 on 2023-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20230205_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='custom_job_code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_code_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='job_code_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
