# Generated by Django 3.2.15 on 2023-02-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_job_custom_job_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
    ]
