# Generated by Django 3.2.15 on 2023-02-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_vendor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='allVendorInvoicesPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cost',
            name='invoice_status',
            field=models.CharField(choices=[('NR', 'Not ready to request'), ('READY', 'Ready to request'), ('REQ', 'Requested'), ('REC', 'Received'), ('PAID', 'Paid'), ('NA', 'No Invoice')], default='--invoice status--', max_length=50),
        ),
        migrations.AlterField(
            model_name='cost',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_rel', to='main_app.vendor'),
        ),
    ]
