# Generated by Django 3.2.15 on 2023-02-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20230207_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='PO_num_is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cost',
            name='invoice_status',
            field=models.CharField(choices=[('NR', 'Not ready to request'), ('READY', 'Ready to request'), ('REQ', 'Requested'), ('REC', 'Received'), ('CHECK', 'Needs manual check'), ('PAID', 'Paid'), ('NA', 'No Invoice')], default='--invoice status--', max_length=50),
        ),
    ]
