# Generated by Django 3.2.15 on 2023-02-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20230215_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_date',
        ),
        migrations.AddField(
            model_name='job',
            name='job_month',
            field=models.CharField(default=2, max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='job_year',
            field=models.CharField(default=2023, max_length=4),
        ),
    ]
