# Generated by Django 3.2.15 on 2023-02-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20230215_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='calc_date',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='month',
            field=models.CharField(default=2, max_length=2),
        ),
    ]
