# Generated by Django 3.2.15 on 2023-02-15 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20230215_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='calc_date',
            field=models.DateField(default=datetime.date(2023, 2, 15), editable=False, null=True),
        ),
    ]
