# Generated by Django 3.2.15 on 2023-02-15 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20230215_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
