# Generated by Django 3.2.15 on 2023-02-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20230216_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='paidTo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
