# Generated by Django 3.2.15 on 2023-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_job_paidto'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isInvoiced',
            field=models.BooleanField(default=False),
        ),
    ]
