# Generated by Django 3.2.15 on 2023-02-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_job_relatedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='invoiceName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
