# Generated by Django 3.2.15 on 2023-02-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_job_invoicename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='relatedJob',
        ),
        migrations.AddField(
            model_name='job',
            name='relatedJobs',
            field=models.ManyToManyField(null=True, related_name='_main_app_job_relatedJobs_+', to='main_app.Job'),
        ),
    ]
