# Generated by Django 3.2.15 on 2023-02-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20230218_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='relatedJobs',
            field=models.ManyToManyField(related_name='_main_app_job_relatedJobs_+', to='main_app.Job'),
        ),
    ]
