# Generated by Django 3.2.15 on 2023-02-23 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_job_relatedjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='currency',
            field=models.CharField(choices=[('¥', 'JPY ¥'), ('US$', 'USD $'), ('CA$', 'CAD $'), ('AU$', 'AUD $'), ('€', 'EUR €'), ('£', 'GBP £')], default='¥', max_length=10),
        ),
        migrations.AlterField(
            model_name='cost',
            name='invoice_status',
            field=models.CharField(choices=[('NR', 'Not ready to request'), ('READY', 'Ready to request'), ('REQ', 'Requested'), ('REC', 'Received'), ('CHECK', 'Needs manual check'), ('PAID', 'Paid'), ('NA', 'No Invoice')], default='NR', max_length=50),
        ),
        migrations.AlterField(
            model_name='cost',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
