# Generated by Django 3.2.15 on 2023-02-28 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_auto_20230223_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='allVendorInvoicesReceivd',
            new_name='allVendorInvoicesReceived',
        ),
        migrations.AlterField(
            model_name='cost',
            name='PO_number',
            field=models.CharField(default=None, editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_rel', to='main_app.vendor'),
        ),
        migrations.AlterField(
            model_name='job',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='jobs_rel', to='main_app.Vendor', verbose_name='vendors involved'),
        ),
    ]
